name: Deploy to Production

on:
  push:
    branches: [ main ]  # 当 main 分支有推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /app/trackpoint/hp-trackpoint-server
            git pull
            docker-compose down
            docker-compose up -d --build